#!/bin/bash

if [ "$1" = "restart" ]; 
then 

	echo "stop screen"
	screen -X -S web_site quit
	echo "start screen"
	sudo -H -u pi screen -d -m -S web_site node /home/pi/AWS/site.js


elif [ "$1" = "status" ];
then
	
elif [ "$1" = "stop" ];
then
	echo "stop screen"
	screen -X -S web_site quit

else 
	echo "panneau d'aide:"
	echo "	restart   relance le site avec un git pull"
	echo "	status    voir si le site fonctionne"
	echo "	stop      stop le site"

fi