#!/bin/bash

echo "web site script"

if [ "$1" = "restart" ]; 
then 
	cd /home/pi/AWS 
	git pull
	echo "stop screen"
	screen -X -S web_site quit &
	echo "start screen"
	screen -dmS web_site /home/pi/AWS/run_site.sh
	screen -ls


elif [ "$1" = "status" ];
then
	ps fax | grep site.js

elif [ "$1" = "stop" ];
then
	echo "stop screen"
	screen -ls 
	screen -X -S web_site quit &
	echo "stop"

else 
	echo "panneau d'aide:"
	echo "	start   relance le site avec un git pull"
	echo "	status    voir si le site fonctionne"
	echo "	stop      stop le site"

fi